<a href="https://colab.research.google.com/github/mrabhi05/Tensorflow/blob/main/Tensorflow-Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Tensor
A Tensor is a generalization of vectors of vectors and matrices to potentially higher dimensions. Internally, Tensorflow represents tensors as n-dimensional arrays of base datatypes.

Tensors are the fundamental aspect of TensorFlow. They are the main objects that are passed around and manipulated through the program. Each tensor represents a partially defined computation that will eventually produce a value.

In [5]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


###Creating Tensors

In [4]:
string = tf.Variable("This is a String", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.int64)

###Rank/Degree of Tensor

Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a tensor of rank 0, also known as scalar.

In [8]:
rank1_tensor = tf.Variable(["Test","OK"], tf.string)
rank2_tensor = tf.Variable([["test","OK"],["test","Yes"]], tf.string)

In [10]:
tf.rank(rank1_tensor)
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

### Shape of Tensors
The shape of the tensor is simply the amount of elements that exists in each dimension. 

In [11]:
rank2_tensor.shape

TensorShape([2, 2])

### Changing the Shape
The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convient to be able to change the shape of the tensor.

In [13]:
tensor1 = tf.ones([1,2,3]) # tf.ones Creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1]) # Reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3,-1]) # -1 tells the tensor to calculate the size of the dimension in that place

Note: The number of elements in the reshaped tensor MUST match the number in the original 

In [15]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


### Types of Tensors
These are commonly used tensors:
*   Variable
*   Constant
*   Placeholder
*   SparseTensor

With the exception of **Variable** all of these tensors are immutable, meaning their value may not change during execution.

We use the variable tensor when we want to potentially change the value of our tensor



### Evaluating Tensors
Getting its value. Since tensors represents a partially computation we will sometimes need to run what's called a session to evaluate a tensor.

In [16]:
with tf.Session() as sess: # Creates a session using the default graph 
  tensor.eval() # Tensor will ofcourse be the name of your tensor 

AttributeError: ignored

## Practice

In [17]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [19]:
t = tf.zeros([5,5,5,5])
print(t)

t = tf.reshape(t,[125,-1])
print(t)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0.